name: ds_delivery
description: App de delivery simples, funcional e inteligente.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Design e Material 3
  dynamic_color: ^1.7.0
  flutter_svg: ^2.0.10

  # Internacionalização
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Estado
  flutter_riverpod: ^2.6.1

  # Navegação
  go_router: ^13.2.3

  # Responsividade
  flutter_screenutil: ^5.9.0

  # HTTP
  dio: ^5.4.3+1

  # Armazenamento local
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2

  # Firebase
  firebase_core: ^3.15.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.5.1
  firebase_messaging: ^15.2.9

  # Geolocalização e Mapas
  geolocator: ^11.0.0
  google_maps_flutter: ^2.5.3

  # Splash e animações
  flutter_native_splash: ^2.4.0
  flutter_animate: ^4.5.0
  rename: ^3.1.0
  flutter_launcher_icons: ^0.14.4
  material_symbols_icons: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png
